const express=require("express")
const app=express()
const cookiPearser=require("cookie-parser")
const connectDB=require("../Backend/src/Config/db")
const authRoutes=require("../Backend/src/Routes/authRoutes")
const messageRoutes=require("../Backend/src/Routes/messageRoutes")
app.use(express.json())
app.use(cookiPearser())
app.use("/api/auth",authRoutes)
app.use("/api/message",messageRoutes)
app.listen(5000,()=>{
    console.log("server run in 5000")
    connectDB()
})